<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com, contato@sigasmart.com.br
 * https://www.sigasmart.com.br
 */

namespace Tall\Kits\Models\Auth\Acl\Models;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Str;
use Tall\Kits\Models\Auth\Acl\Concerns\HasPermissions;
use Tall\Kits\Models\Auth\Acl\Contracts\Role;
use Tall\Kits\Models\AbstractModel;

abstract class AbstractRole extends AbstractModel implements Role
{

    use HasPermissions;

    /**
     * The attributes that are fillable via mass assignment.
     *
     * @var array
     */
    //protected $fillable = ['name', 'slug', 'description', 'special', 'status'];

    /**
     * Create a new Role instance.
     *
     * @param array $attributes
     * @return void
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable(config('acl.tables.roles'));
    }

    public function getAttributeSlug($value)
    {

        $this->slug = Str::slug($this->name);
    }

    public function getAccessAttribute()
    {

        return $this->permissions()->pluck('name', 'id');
    }

    public function access()
    {

        return $this->permissions();
    }

    public function isUser()
    {
        return false; // TODO: Change the autogenerated stub
    }

    /**
     * Roles can belong to many users.
     *
     * @return BelongsToMany
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(config('auth.model') ?: config('auth.providers.users.model'))->withTimestamps();
    }

    /**
     * Determine if role has permission flags.
     *
     * @return bool
     */
    public function hasPermissionFlags(): bool
    {
        return !is_null($this->special);
    }

    /**
     * Determine if the requested permission is permitted or denied
     * through a special role flag.
     *
     * @return bool
     */
    public function hasPermissionThroughFlag(): bool
    {
        if ($this->hasPermissionFlags()) {
            return !($this->special === 'no-access');
        }

        return true;
    }
}
